### ISSUE TITLE
Cosmetic fault codes after upgrading

### ISSUE THREAD

**Issue by dalathegreat** [dalathegreat/Nissan-env200-Battery-Upgrade#2]
Some fault codes will be active after upgrading, these are harmless but annoying. Attached a Leafspy DTC scan screenshot:

![image](https://user-images.githubusercontent.com/26695010/155860285-56d49f5d-188f-4d8f-9da4-03a49d334f9d.png)

This needs to be solved by generating some missing CAN-messages towards the battery. CAN-Log from native 2018+ env200 40kWh EV-CAN would be awesome for solving this, any help welcome!

**Comment by dalathegreat** [comment]
With the above mentioned PR being merged, we are now down to 2 fault codes!

![image](https://user-images.githubusercontent.com/26695010/157261188-47fb2788-8ca8-4aec-b339-89d088360595.png)

Very cosmetic issue now, but it would be amazing to get rid of these. Anyone got any log files from a native 2018+ env200 EV-CAN?

**Comment by glynhudson** [comment]
I think these remaining error codes are due to the 40kWh battery upgrade (pairing via LeafSpy) rather than caused by the CAN bridge. These codes are still present when the CAN bridge is disconnected. I'll let you know if I managed to access a native 40kWh van.

**Comment by dalathegreat** [comment]
Absolutely is. The U1000 code is a generic "Hey there is something wrong with the CAN data". There are probably many small differences between the 24 and 40kWh EV-CAN data.

Reasons could be:
- Some CAN-message might have changed length (e.g.5-8bytes)
- Some CAN-messages might be missing (like the previous PR fixed a missing cluster message)
- Some CAN-messages might be transmitted at wrong periodic rate (e.g 100 instead of 10ms)
- Other reasons

This might be very hard to solve, but I would be willing to have a go at it just to perfect this upgrade type :)

**Comment by dalathegreat** [comment]
I am happy to announce that this was completely fixed now 🥳 

The commit 37b1f1fc798d3c82bf6fab96385e8560b9bb7744 adds the missing EV-CAN messages that the ZE1 40kWh expects. We now have solved the final piece of the puzzle, and the env200 40kWh upgrade code can be considered stable and complete 👍 

Closing this issue!

**Comment by glynhudson** [comment]
I can confirm, tested and working on my 24kWh > 40kWh upgrade van. No DTCs are remaining, nice work Dala :+1: 

![Screenshot_20220705-123410](https://user-images.githubusercontent.com/758844/178022470-3dae5f1d-8ad9-47ea-bb1d-94e643fc0998.jpg)
